apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: api-ingress
spec:
  tls:
    - hosts:
        - api.openeuler.org
      secretName: api-tls
  rules:
    - host: api.openeuler.org
      http:
        paths:
          - backend:
              serviceName: pkgmanage-service-release
              servicePort: 80
            path: /pkgmanage(/|$)(.*)
          - backend:
              serviceName: pkgmanage-service-debug
              servicePort: 80
            path: /pkgmanagedebug(/|$)(.*)
          - backend:
              serviceName: mailman-service
              servicePort: 8001
            path: /mailman(/|$)(.*)
          - backend:
              serviceName: meeting-service
              servicePort: 80
            path: /meetings(/|$)(.*)
          - backend:
              serviceName: bot-debug-service
              servicePort: 8888
            path: /botdebug(/|$)(.*)

