resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: sync-bot
namespace: sync-bot
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/sync-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/sync-bot
  newTag: 308b607c092fa60ac83c7186efc9f87ca69791e5
