---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-sync-bot-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: ssd
