resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-debug
nameSuffix: -debug
namespace: bot-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newTag: 059002f49174814e4853a108bf00e87336c3a7c2.1599137023
