resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-debug
nameSuffix: -debug
namespace: bot-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
- secrets.yaml
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newTag: c230aa529986a16df97e7384304fc1eb6f1c5ca6.1609307649
