resources:
- https://github.com/opensourceways/app-patchtracking/deploy?ref=master
commonLabels:
  app: openeuler-patchtracking-release
nameSuffix: -release
namespace: patch-tracking-release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/patchtracking
  newName: opensourceway/patchtracking
  newTag: 202a7c04122d3afa5663bbdfa547358635248011.1602559514
