apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: website-v2-ingress-backend
spec:
  tls:
    - hosts:
        - openeuler.org
      secretName: website-v2-tls-main-secret
  rules:
    - host: openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-backend-service
              servicePort: 80
            path: /api(/|$)(.*)
          - backend:
              serviceName: openeuler-bot-internal
              servicePort: 8888
            path: /api-cla(/|$)(.*)
          - backend:
              serviceName: openeuler-meetingserver-internal
              servicePort: 80
            path: /api-sig(/|$)(.*)
          - backend:
              serviceName: cve-srv-service
              servicePort: 8080
            path: /api-cve(/|$)(.*)
