resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress-backend.yaml
- secrets.yaml
- ingress-main.yaml
- cibot-service.yaml
- www-ingress.yaml
- meeting-service.yaml
- cve-backend.yaml
- purge-cache.yaml
- purge-secrets.yaml
- oauth-proxy.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: newyear-backend
    path: selector.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: newyear-frontend
    path: selector.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newTag: f6bcb0cef0bc027ca5cc5b4ac87120ed557eca1d
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newTag: f6bcb0cef0bc027ca5cc5b4ac87120ed557eca1d
