resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress-backend.yaml
- secrets.yaml
- ingress-main.yaml
- cibot-service.yaml
- www-ingress.yaml
- meeting-service.yaml
- cve-backend.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newTag: 187afb7fa9ac3f539c7139047852b010cf15212a
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newTag: 187afb7fa9ac3f539c7139047852b010cf15212a
