resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress-backend.yaml
- secrets.yaml
- ingress-main.yaml
- cibot-service.yaml
- www-ingress.yaml
- meeting-service.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newTag: 0f1097fcecc7b6436d134735781b6c774e08e99b
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newTag: 0f1097fcecc7b6436d134735781b6c774e08e99b
