resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress-backend.yaml
- secrets.yaml
- ingress-main.yaml
- cibot-service.yaml
- www-ingress.yaml
- meeting-service.yaml
- cve-backend.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newTag: a73ccf289ae89ca49cdfe8c6733c6e673922a6bf
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newTag: a73ccf289ae89ca49cdfe8c6733c6e673922a6bf
