resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress-main.yaml
- ingress-backend.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
