---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    spec:
      containers:
        - name: jenkins
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: openeuler-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: openeuler-jenkins
          resources:
            limits:
              cpu: 12000m
              memory: 16000Mi
            requests:
              cpu: 6000m
              memory: 8000Mi
      initContainers:
        - name: copy-default-config
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: openeuler-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: openeuler-jenkins
