---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openeuler-jenkins-es
spec:
  name: openeuler-jenkins-es
  keysMap:
    es_url:
      path: secrets/data/openeuler/jenkins
      key: es_url
    es_username:
      path: secrets/data/openeuler/jenkins
      key: es_username
    es_password:
      path: secrets/data/openeuler/jenkins
      key: es_password
