apiVersion: v1
kind: Service
metadata:
  # jenkins is configured with EIP in case of low visit speed if we visit this web via jenkins.openeuler.org
  name: jenkins
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: bbc8c833-6015-4847-9a87-06fdfc1e71c5
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  loadBalancerIP: 114.116.250.98
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: slavelistener
      port: 50000
      targetPort: 50000
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
spec:
  ports:
    - name: http
      port: 80
      # we need pin the node port here in order to be visitable via node
      targetPort: 8080
      nodePort: 30080
    - name: slavelistener
      port: 50000
      # we need pin the node port here in order to be visitable via node
      nodePort: 30050
      targetPort: 50000
  type: NodePort
