apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    # We added EIP here for the case of low speed when visit via jenkins.openeuler.org
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 062f876f-544f-47b7-9ee9-ac6bdcb3f7e8
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: slavelistener
      port: 50000
      targetPort: 50000
  externalTrafficPolicy: Cluster
  loadBalancerIP: 119.8.127.55
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
spec:
  ports:
    - name: slavelistener
      port: 50000
      # we need pin the node port here in order to be visitable via node
      nodePort: 30050
      targetPort: 50000
  type: NodePort
