resources:
- deployment.yaml
- secrets.yaml
commonLabels:
  app: cve-manager-analysis
namespace: cve-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/cve-manager-analysis
  newTag: 7c2a10e2064a87c33472c23188a3f90a613a309b
