resources:
- deployment.yaml
- namespace.yaml
- service.yaml
namespace: summary
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newTag: 000dea1165f6381c20e4ab4285f07de7e68f7cc2
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newTag: 48634bac1db03eec3895ec20462d5e4a6c24544c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newTag: cecb887c01573de334433108863ba0d95d0e2b50
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newTag: 2d5a8f811ac1b0483715f4a30ea2c3556baea78e
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newTag: 79a3dac89eb5dd7d0f79db6705d72dfc5b2d5f33
