resources:
- deployment.yaml
- namespace.yaml
- service.yaml
namespace: summary
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newTag: 2d9da723a2826aa61a4cc0dad85d560d85544dbb
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newTag: 48634bac1db03eec3895ec20462d5e4a6c24544c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newTag: 823afde24fa7fcdcc555d2f6310d6258bb40470c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newTag: 73c4737e90fb6431edeb392c5a904c2e39f31b04
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newTag: d7d439a9fc02bb0b3de8feed0378653bcee1cefc
