resources:
- deployment.yaml
- namespace.yaml
- service.yaml
namespace: summary
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newTag: 30295bfb2aa6d8528633e7f130d176d505546366
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newTag: 48634bac1db03eec3895ec20462d5e4a6c24544c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newTag: 33b57fa14f2dfe7d173ea876d95d83e2c1911d28
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newTag: 23c9e0f90b406d9233742cc1b2036cdd4192ab34
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newTag: 30f31834064c032f4222ba6948fbb52f415eba53
