resources:
- deployment.yaml
- namespace.yaml
- service.yaml
namespace: summary
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newTag: d3905abe0561426735f9ba09a5000b977d8cbd2c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newTag: 48634bac1db03eec3895ec20462d5e4a6c24544c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newTag: c6374c47d06f1a97ef369b3f2d43da30735b2fda
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newTag: 6720ff83629666a8729947cc41b8b5060bddd2c3
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openlookeng-newyear
  newTag: 2cd5f8615a5f0779141f26915f1a0b87c6711ad5
