resources:
- deployment.yaml
- namespace.yaml
- service.yaml
commonLabels:
  app: summary
namespace: summary
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bless-server
  newTag: 6a02da500f88597d129cdd39d67f5153e62368a5
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-newyear
  newTag: 48634bac1db03eec3895ec20462d5e4a6c24544c
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-newyear
  newTag: aa63cb97b766ad588eafb1e6ab0b50a6b28f69ce
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/opengauss-newyear
  newTag: 90293df27a7306088034fe5c9ed6c8be878987b8
