resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 1582a759c1730bd60f8f471abedf198d9ca7b16c.1598082384
