resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 63155eb517c95160ddd648c956d5e78a19dad605.1602658687
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 63155eb517c95160ddd648c956d5e78a19dad605.1602658687
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: 1587c5d044c91434cb51a72f60da3b1d61d82321.1602592316
