resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 0c4da6c3691b9a0448e116d2ecc89d00e7cb2c86.1598252511
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 0c4da6c3691b9a0448e116d2ecc89d00e7cb2c86.1598252511
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: c8d4ab3f54220bac5efdefcfb7a6fa93baaceebb.1598514079
