resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 239ed6034fa997e54f6ee654195fb5acd8cc8e7e.1599480304
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 239ed6034fa997e54f6ee654195fb5acd8cc8e7e.1599480304
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: c1f251e49e4bb7516fb819ef139e574c72d9882f.1598853443
