resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 2bb400f467d5565aebdd89657c3496988c352e4d.1602589026
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 2bb400f467d5565aebdd89657c3496988c352e4d.1602589026
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: 4a3aad6086216346a2b2c81727cafa2f72a25a08.1602592285
