resources:
  - https://github.com/opensourceways/app-ssh-tunnel/deploy?ref=stable
  - secrets.yaml
  - namespace.yaml
commonLabels:
  app: openeuler-ssh-tunnel
patchesStrategicMerge:
  - service.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ssh-tunnel
    path: deployment.json
namespace: ssh-tunnel2


