apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updating-openeuler-sigs
spec:
  schedule: "* */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: meeting-server
              image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/app-meeting-server:220294c21a65397a9b88c20daba77d4a3a2d6dff
              volumeMounts:
                - mountPath: /work/app-meeting-server/community_meetings/settings.py
                  name: meeting-server-secrets-volume
                  subPath: settings
              env:
                - name: ZOOM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: zoom_token
                      name: meeting-server-secrets
              command:
                - /bin/sh
                - -c
                - |
                  python manage.py genegroup
          volumes:
            - name: meeting-server-secrets-volume
              secret:
                secretName: meeting-server-secrets
