# Deployment for meeting service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: meeting-server
spec:
  selector:
    matchLabels:
      app: meeting-server
  template:
    metadata:
      labels:
        app: meeting-server
    spec:
      containers:
        - name: meeting-server
          image: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/app-meeting-server:220294c21a65397a9b88c20daba77d4a3a2d6dff
          volumeMounts:
            - mountPath: /work/app-meeting-server/community_meetings/settings.py
              name: meeting-server-secrets-volume
              subPath: settings
            - mountPath: /work/app-meeting-server/meetings/migrations
              name: meeting-data-volume
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          env:
            - name: ZOOM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: zoom_token
                  name: meeting-server-secrets
          command:
            - /bin/sh
            - -c
            - |
              # incase the __init__.py does not exist in the mounted volume
              touch /work/app-meeting-server/meetings/migrations/__init__.py
              python manage.py collectstatic
              python manage.py makemigrations
              python manage.py migrate
              uwsgi --ini /work/app-meeting-server/deploy/production/uwsgi.ini
      volumes:
        - name: meeting-server-secrets-volume
          secret:
            secretName: meeting-server-secrets
        - name: meeting-data-volume
          persistentVolumeClaim:
            claimName: meeting-data-volume

