resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- cronjob.yaml
- pvc.yaml
commonLabels:
  app: openeuler-meetingserver
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meetingserver
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/app-meeting-server
  newTag: c286b7f74c552a320dceb815b1c7ade680a69c72
