---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-data-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ssd