apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: e053029b-1898-4665-89eb-6ab598e448d7
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  name: botservice
  namespace: bot
spec:
  clusterIP: 10.247.135.196
  externalTrafficPolicy: Cluster
  loadBalancerIP: 159.138.49.225
  ports:
    - name: httpport
      nodePort: 31200
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: botinfo
  type: LoadBalancer