apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: meetbot-secret
spec:
  name: meetbot-secret
  keysMap:
    irc_password:
      path: secrets/data/openeuler/meetingbot
      key: irc_password
