apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: ssh-tunnel-secrets
spec:
  name: ssh-secrets
  keysMap:
    public_keys:
      path: secrets/data/infra-common/ssh-keys
      key: public_keys
    private_keys:
      path: secrets/data/infra-common/ssh-keys
      key: private_keys
