apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://www.openlookeng.io
  name: openlookeng-website-ingress-main
spec:
  rules:
    - host: openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-website-internal
              servicePort: 80
            path: /
