apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openlookeng-website
spec:
  name: openlookeng-website
  keysMap:
    client_id:
      path: secrets/data/infra-common/gitee-applications/openlookeng-website
      key: client_id
    client_secret:
      path: secrets/data/infra-common/gitee-applications/openlookeng-website
      key: client_secret
    cookie_secret:
      path: secrets/data/infra-common/gitee-applications/openlookeng-website
      key: cookie_secret
