---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/permanent-redirect: https://openlookeng.io
  name: openlookeng-website-ingress
spec:
  tls:
    - hosts:
        - www.openlookeng.io
      secretName: openlookeng-website-tls
  rules:
    - host: www.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-website-internal
              servicePort: 80
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Groups, X-Auth-Request-Email, X-Auth-Request-Preferred-Username"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: website-ingress-protected
spec:
  tls:
    - hosts:
        - openlookeng.io
      secretName: openlookeng-website-tls-main
  rules:
    - host: openlookeng.io
      http:
        paths:
          - backend:
              serviceName: newyear-frontend
              servicePort: 80
            path: /events(/|$)(.*)
