apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: openlookeng-repo-ingress
spec:
  tls:
    - hosts:
        - download.openlookeng.io
      secretName: openlookeng-repo-tls
  rules:
    - host: download.openlookeng.io
      http:
        paths:
          - backend:
              serviceName: openlookeng-repo-internal
              servicePort: 80
            path: /
