resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - pvc.yaml
  - namespace.yaml
  - secrets.yaml
commonLabels:
  app: openeuler-cn-north4-dailybuild-repo
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
namespace: dailybuild


