apiVersion: v1
kind: Service
metadata:
  name: repo-service
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: ffb0d76f-638f-4612-9827-7e343c434803
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  loadBalancerIP: 121.36.53.23
  externalTrafficPolicy: Cluster
  ports:
    - name: rsync-ssh-server-port
      port: 22
      targetPort: 22
      # used to be visitable via nodeport
      nodePort: 30122