resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 2bb400f467d5565aebdd89657c3496988c352e4d.1602590541
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 2bb400f467d5565aebdd89657c3496988c352e4d.1602590541
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: c1f251e49e4bb7516fb819ef139e574c72d9882f.1598849043
