resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 21a245c3711e6bbbdb99c51c558cd6561e71b3f3.1603105411
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 21a245c3711e6bbbdb99c51c558cd6561e71b3f3.1603105411
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: f619a3723cf1a868235233be0e9615cd905995b8.1602592417
