resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: ce6ad0d7c54dec3dbf37951579ce705f17e5407a.1598840011
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: ce6ad0d7c54dec3dbf37951579ce705f17e5407a.1598840011
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: acc12fe0fa3290dde158b9dd91b64f6b0b1f50ea.1598697201
