resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: ab970d27dc358acef8804eb3677de541411eaee0.1603873940
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: ab970d27dc358acef8804eb3677de541411eaee0.1603873940
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: 389acc726688d0aa8d3f1b38cadd78bd3f8bbb5b.1605511292
