resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 48794f944713304ff49397361f93d3ec612f3c3d.1598239434
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 48794f944713304ff49397361f93d3ec612f3c3d.1598239434
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: acc12fe0fa3290dde158b9dd91b64f6b0b1f50ea.1598697201
