resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: ab970d27dc358acef8804eb3677de541411eaee0.1603873940
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: ab970d27dc358acef8804eb3677de541411eaee0.1603873940
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: ab10a983c32e0d8ff9d605f906829845c017df62.1605063064
