resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: 99bde1c3e1fc46ba4549471fa0ffd273df6ad743.1603088207
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: 99bde1c3e1fc46ba4549471fa0ffd273df6ad743.1603088207
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: f619a3723cf1a868235233be0e9615cd905995b8.1602592417
