resources:
- namespace.yaml
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-dbug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/packagemanage
  newTag: 16bcb44fec7697dd69db25eff986cf0921c7b939.1597827739
