resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: opensourceway/dbgetinit
  newTag: ecba792fc7d8061f9767d9e6eba337b072b112dc.1603072838
- name: opensourceway/packagemanage
  newName: opensourceway/packagemanage
  newTag: ecba792fc7d8061f9767d9e6eba337b072b112dc.1603072838
- name: opensourceway/pkgmanageweb
  newName: opensourceway/pkgmanageweb
  newTag: f619a3723cf1a868235233be0e9615cd905995b8.1602592417
