resources:
- https://github.com/opensourceways/infra-openeuler/applications/openeuler-website-v2?ref=master
- secrets.yaml
commonLabels:
  app: openeuler-website-v2
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ingress-backend.yaml
- ingress-main.yaml
- remove-wwwingress.yaml
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-backend
  newTag: 924e91183ea85f1aa0f1cfbea30444ca9a9162a2
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/openeuler-website-frontend
  newTag: 924e91183ea85f1aa0f1cfbea30444ca9a9162a2
