# ssh-tunnel service
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-tunnel
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: b0fa0739-f69c-4abd-bcbf-840c8dd1b44e
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  loadBalancerIP: 114.116.245.239
