resources:
- https://github.com/opensourceways/app-patchtracking/deploy?ref=master
commonLabels:
  app: openeuler-patchtracking-debug
nameSuffix: -debug
namespace: patch-tracking-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/patchtracking
