resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-release
nameSuffix: -release
namespace: bot-release
apiVersion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- deployment.yaml
kind: Kustomization
images:
- name: opensourceway/openeulerbot:v1.0
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newTag: dfe68e6c8ca5d23dd816f3a399e81773e207833c.1604311982
