resources:
- https://github.com/opensourceways/app-bot/deploy?ref=master
commonLabels:
  app: openeuler-bot-release
nameSuffix: -release
namespace: bot-release
apiVersion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
  - deployment.yaml
kind: Kustomization
images:
- name: opensourceway/openeulerbot:v1.0
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/ci-bot
  newTag: 20ff9f8bd1b40a987a368229c30013b9311d9f45.1599812654
