resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - pvc.yaml
  - namespace.yaml
  - secrets.yaml
  - ingress.yaml
commonLabels:
  app: openeuler-repo-mirror-hk
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
namespace: repo-mirror


