resources:
  - ingress.yaml
  - namespace.yaml
  - service.yaml
commonLabels:
  app: openeuler-etherpad
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: etherpad-internal
    path: selector.yaml
namespace: etherpad
