apiVersion: v1
kind: Service
metadata:
  name: cve-srv-service
spec:
  ports:
    - name: srv
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cve-backend-info
  type: ClusterIP
