resources:
  - ingress.yaml
  - namespace.yaml
  - service.yaml
commonLabels:
  app: blog
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: website-blog-internal
    path: selector.yaml
namespace: blog
